Update patchscript template

diff --git a/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript b/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript
--- a/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript
+++ b/ports/released/gamemakerengine/madhouse/madhouse/tools/patchscript
@@ -16,35 +16,7 @@ patch_failure() {
     return 1 2>/dev/null || exit 1
 }
 
-# Mount the GMToolkit runtime
-TOOLKIT="$HOME/gmtoolkit"
-RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
-if [ -f "$RUNTIME" ]; then
-    $ESUDO mkdir -p "$TOOLKIT"
-    $ESUDO umount "$TOOLKIT" 2>/dev/null || true
-    $ESUDO mount "$RUNTIME" "$TOOLKIT"
-else
-    echo "This port requires the GMToolkit runtime. Please download it."
-    sleep 2
-    patch_failure
-fi
-
-# Mount the dotnet runtime
-DOTNETDIR="$HOME/mono"
-DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
-if [ -f "$DOTNETFILE" ]; then
-    $ESUDO mkdir -p "$DOTNETDIR"
-    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
-    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
-else
-    echo "This port requires the Dotnet runtime. Please download it."
-    sleep 2
-    patch_failure
-fi
-
 # Exports
-export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
-export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
 export SDL_GAMECONTROLLERCONFIG="$sdl_controllerconfig"
 export DATADIR="$GAMEDIR/assets"
 export DATAFILE="madhouse.port"
@@ -65,18 +37,48 @@ else
     SAVEDIR="$GAMEDIR/saves"
 fi
 
-# Test for commands: python, zip
-PYTHON=$(which python3)
-if [ -z "$PYTHON" ]; then
-    echo "Missing Python!"
-    patch_failure
-fi
+prepare_system() {
+    # Test for commands: python, zip
+    PYTHON=$(which python3)
+    if [ -z "$PYTHON" ]; then
+        echo "Missing Python!"
+        return 1
+    fi
 
-ZIP=$(which zip)
-if [ -z "$ZIP" ]; then
-    echo "Missing zip!"
-    patch_failure
-fi
+    ZIP=$(which zip)
+    if [ -z "$ZIP" ]; then
+        echo "Missing zip!"
+        return 1
+    fi
+    
+    # Mount the GMToolkit runtime
+    TOOLKIT="$HOME/gmtoolkit"
+    RUNTIME="$controlfolder/libs/gmtoolkit.squashfs"
+    if [ -f "$RUNTIME" ]; then
+        $ESUDO mkdir -p "$TOOLKIT"
+        $ESUDO umount "$TOOLKIT" 2>/dev/null || true
+        $ESUDO mount "$RUNTIME" "$TOOLKIT"
+    else
+        echo "This port requires the GMToolkit runtime. Please download it."
+        return 1
+    fi
+
+    # Mount the dotnet runtime
+    DOTNETDIR="$HOME/mono"
+    DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+    if [ -f "$DOTNETFILE" ]; then
+        $ESUDO mkdir -p "$DOTNETDIR"
+        $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
+        $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+    else
+        echo "This port requires the Dotnet runtime. Please download it."
+        return 1
+    fi
+    
+    # Exports
+    export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
+    export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
+}
 
 # Prepare game data
 # If there are audiogroups in the madhouse.port file, unzip them
@@ -129,6 +131,26 @@ replace_code() {
     fi
 }
 
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
+    else
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
 # Compress audio files inside datafile and audiogroups
 compress_audio() {
     # Purge cache before operations
@@ -158,8 +180,7 @@ compress_audio() {
         echo "Audio compression applied successfully."
     else
         # Failure
-        echo "Audio compression failed
-        ."
+        echo "Audio compression failed."
         rmdir "$TMPDIR"
         return 1
     fi
@@ -167,17 +188,25 @@ compress_audio() {
 
 # Zip it all into the .port file
 zip_archive() {
-        zip -r -0 $DATAFILE ./assets/
-        mkdir -p saves
-        rm -rf $DATADIR/*
+    if zip -r -0 "$DATAFILE" ./assets/; then
+        mkdir -p "$SAVEDIR"
+        rm -rf "$DATADIR"/*
+    else
+        echo "Failed to create $DATAFILE."
+        return 1
+    fi
 }
 
 # Main function
 process_game() {
+    echo "Preparing system..."
+    prepare_system || { patch_failure; return 1; }
     echo "Preparing game files..."
-    prepare_files
+    prepare_files || { patch_failure; return 1; }
     echo "Adding modified scripts..."
     replace_code || { patch_failure; return 1; }
+    echo "Toggling GeneralInfo flags..."
+    set_flags || { patch_failure; return 1; }
     echo "Compressing audio..."
     compress_audio || { patch_failure; return 1; }
     echo "Finishing up..."
