Further optimize GMS ports by reeplacing xdeltas with in-place modifications via set_flags

diff --git a/ports/released/gamemakerengine/darkdeity/darkdeity/tools/patchscript b/ports/released/gamemakerengine/darkdeity/darkdeity/tools/patchscript
--- a/ports/released/gamemakerengine/darkdeity/darkdeity/tools/patchscript
+++ b/ports/released/gamemakerengine/darkdeity/darkdeity/tools/patchscript
@@ -95,47 +95,23 @@ prepare_files() {
     fi
 }
 
-# Apply a patch to enforce stretching to fill the display
-apply_xdelta() {
-    GOG_MD5="1c3ac1d5c2bb7d3c49f601d21b2e584d"
-    STEAM_MD5="2a491f42eea91f76b838c7196430afe9"
-
-    if [ -f "$DATADIR/data.win" ]; then
-        checksum=$(md5sum "$DATADIR/data.win" | awk '{print $1}')
-        case "$checksum" in
-            "$GOG_MD5")
-                PATCH="darkdeity_gog.xdelta"
-                ;;
-            "$STEAM_MD5")
-                PATCH="darkdeity_steam.xdelta"
-                ;;
-            *)
-                echo "Unknown data.win checksum: $checksum"
-                echo "Cannot determine appropriate patch"
-                patch_failure
-                return
-                ;;
-        esac
-
-        if [ -f "$GAMEDIR/tools/$PATCH" ]; then
-            output=$($controlfolder/xdelta3 -d -s "$DATADIR/data.win" -f "$GAMEDIR/tools/$PATCH" "$DATADIR/data2.win" 2>&1)
-            if [ $? -eq 0 ]; then
-                echo "Patch applied successfully"
-                echo "$output"
-                rm "$DATADIR/data.win" && mv "$DATADIR/data2.win" "$DATADIR/data.win"
-                sleep 1
-            else
-                echo "Failed to apply patch"
-                echo "$output"
-                patch_failure
-            fi
-        else
-            echo "Patch file not found: $GAMEDIR/tools/$PATCH"
-            patch_failure
-        fi
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
     else
-        echo "data.win not found in $DATADIR"
-        patch_failure
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
     fi
 }
 
@@ -161,36 +137,42 @@ dump_textures() {
     [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
 }
 
-compress_audio() {  
-    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -v -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
+compress_audio() {
+    # Test for data.win
+    if [ -f "$DATADIR/data.win" ]; then
+        mv "$DATADIR/data.win" "$DATADIR/game.droid"
+    fi
+    
+    # Do audio compression
+    if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
         mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
         echo "Audio compression applied successfully."
     else
         # Failure
-        echo "Audio compression failed for $GAMEFILE."
+        echo "Audio compression failed."
         rmdir "$TMPDIR"
-        patch_failure
+        return 1
     fi
 }
 
 zip_archive() {
-        zip -r -0 "$DATAFILE" ./assets/
-        echo "Zipped contents to $DATAFILE"
-        rm -rf "$GAMEDIR/assets/"*
+    $ZIP -r -0 "$DATAFILE" ./assets/
+    echo "Zipped contents to $DATAFILE"
+    rm -rf "$DATADIR/"*
 }
 
 process_game() { 
     echo "Preparing game..."
-    prepare_files || patch_failure 
-    echo "Applying xdelta patch..."
-    apply_xdelta || patch_failure
+    prepare_files || { patch_failure; return 1; }
+    echo "Toggling GeneralInfo flags..."
+    set_flags || { patch_failure; return 1; }
     echo "Externalizing textures..."
-    dump_textures || patch_failure
+    dump_textures || { patch_failure; return 1; }
     echo "Compressing audio..."
-    compress_audio || patch_failure
+    compress_audio ||| { patch_failure; return 1; }
     sleep 1
     echo "Finishing up..."
-    zip_archive || patch_failure
+    zip_archive || { patch_failure; return 1; }
     sleep 1
     
     # Unmount runtimes
diff --git a/ports/released/gamemakerengine/lunarlux/lunarlux/tools/patchscript b/ports/released/gamemakerengine/lunarlux/lunarlux/tools/patchscript
--- a/ports/released/gamemakerengine/lunarlux/lunarlux/tools/patchscript
+++ b/ports/released/gamemakerengine/lunarlux/lunarlux/tools/patchscript
@@ -29,6 +29,19 @@ else
     patch_failure
 fi
 
+# Mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+    $ESUDO mkdir -p "$DOTNETDIR"
+    $ESUDO umount "$DOTNETFILE" || true
+    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+    echo "This port requires the Dotnet runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
 # Exports
 export PATH="$DOTNETDIR:$TOOLKIT/gmtools:$TOOLKIT/utmt-cli:$PATH"
 export LD_LIBRARY_PATH="/usr/lib:$TOOLKIT/libs:$LD_LIBRARY_PATH"
@@ -65,49 +78,70 @@ if [ -z "$ZIP" ]; then
     patch_failure
 fi
 
-apply_xdelta() {
-    # Check if the data.win file exists and apply xdelta
-    if [ -f "$DATADIR/data.win" ]; then
-        output=$(xdelta3 -d -s "$DATADIR/data.win" -f "./tools/patches/lunarlux.xdelta" "$DATADIR/game.droid" 2>&1)
-        if [ $? -eq 0 ]; then
-            echo "Patch applied successfully"
-            echo "$output"
-            rm "$DATADIR/data.win"
-        else
-            echo "Failed to apply patch"
-            echo "$output"
-            exit 1
-        fi
-    else
-        echo "No data.win file found to patch!"
+prepare_files() {
+    mkdir -p "$SAVEDIR"
+    
+    # Delete excess files
+    find "$DATADIR" -type f \( \
+        -name "*.exe" -o -name "*.dll" -o -name "*.hashdb" -o \
+        -name "*.ico" -o -name "*.lnk" -o -name "*.msg" -o -name "*.zip" \
+    \) -exec rm -f {} \;
+
+    # Move splash file if it exists
+    if [ -f "$DATADIR/splash.png" ]; then
+        mv "$DATADIR/splash.png" "$GAMEDIR/splash.png"
     fi
 }
 
-compress_audio() {  
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
+    else
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
+compress_audio() {
+    # Test for data.win
+    if [ -f "$DATADIR/data.win" ]; then
+        mv "$DATADIR/data.win" "$DATADIR/game.droid"
+    fi
+    
+    # Do audio compression
     if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
         mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
         echo "Audio compression applied successfully."
     else
         # Failure
-        echo "Audio compression failed for $GAMEFILE."
+        echo "Audio compression failed."
         rmdir "$TMPDIR"
-        patch_failure
+        return 1
     fi
 }
 
 zip_archive() {
-        zip -r -0 $DATAFILE ./assets/
-        rm -rf ./assets
-        mkdir -p saves
+    $ZIP -r -0 "$DATAFILE" ./assets/
+    echo "Zipped contents to $DATAFILE"
+    rm -rf "$DATADIR/"*
 }
 
 process_game() {
-    # Delete unnecessary files
-    rm -rf $DATADIR/*.exe $DATADIR/*.dll $DATADIR/.gitkeep
-    echo "Removed unnecessary files"
-
-    echo "Applying xdelta patch"
-    apply_xdelta || { patch_failure; return 1; }
+    echo "Preparing game..."
+    prepare_files || { patch_failure; return 1; }
+    echo "Toggling GeneralInfo flags..."
+    set_flags || { patch_failure; return 1; }
     echo "Compressing audio..."
     compress_audio || { patch_failure; return 1; }
     echo "Finishing up..."
diff --git a/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript b/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
--- a/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
+++ b/ports/released/gamemakerengine/sonictt16b/sonictt16b/tools/patchscript
@@ -10,6 +10,7 @@ echo "GAMEDIR is set to: $GAMEDIR"
 
 # Patch failure function
 patch_failure() {
+    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
     $ESUDO umount "$TOOLKIT" 2>/dev/null || true
     # Exit script, or return if sourced
     return 1 2>/dev/null || exit 1
@@ -90,48 +91,56 @@ unzip_apk() {
     fi
 }
 
-apply_xdelta() {
-    # Check if the game.droid file exists and apply xdelta
-    if [ -f "$DATADIR/game.droid" ]; then
-        output=$($controlfolder/xdelta3 -d -s "$DATADIR/game.droid" -f "$TOOLDIR/patches/sonictt16b.xdelta" "$DATADIR/game2.droid" 2>&1)
-        if [ $? -eq 0 ]; then
-            echo "Patch applied successfully"
-            echo "$output"
-            rm "$DATADIR/game.droid" && mv "$DATADIR/game2.droid" "$DATADIR/game.droid"
-        else
-            echo "Failed to apply patch"
-            echo "$output"
-            return 1
-        fi
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
     else
-        echo "No data.win file found to patch!"
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
     fi
 }
 
-compress_audio() {  
+compress_audio() {
+    # Test for data.win
+    if [ -f "$DATADIR/data.win" ]; then
+        mv "$DATADIR/data.win" "$DATADIR/game.droid"
+    fi
+    
+    # Do audio compression
     if $PYTHON "$TOOLKIT/gmtools/gmKtool.py" -vv -m 1000 -r -b 64 -d "$TMPDIR" "$DATADIR/game.droid"; then
         mv "$TMPDIR/"* "$DATADIR" && rmdir "$TMPDIR"
         echo "Audio compression applied successfully."
     else
         # Failure
-        echo "Audio compression failed for $GAMEFILE."
+        echo "Audio compression failed."
         rmdir "$TMPDIR"
         return 1
     fi
 }
 
 zip_archive() {
-        $ZIP -r -0 $DATAFILE ./assets/
-        mkdir -p saves
-        rm -rf assets
+    $ZIP -r -0 "$DATAFILE" ./assets/
+    echo "Zipped contents to $DATAFILE"
+    rm -rf "$DATADIR/"*
 }
 
 process_game() {
 
     echo "Looking for apk file..."
     unzip_apk || { patch_failure; return 1; }
-    echo "Applying xdelta patch"
-    apply_xdelta || { patch_failure; return 1; }
+    echo "Toggling GeneralInfo flags..."
+    set_flags || { patch_failure; return 1; }
     echo "Compressing audio..."
     compress_audio || { patch_failure; return 1; }
     echo "Finishing up..."
@@ -147,4 +156,5 @@ else
 fi
 
 # Unmount runtimes
+$ESUDO umount "$DOTNETDIR" 2>/dev/null || true
 $ESUDO umount "$TOOLKIT" 2>/dev/null || true
diff --git a/ports/released/gamemakerengine/triga/triga/tools/patchscript b/ports/released/gamemakerengine/triga/triga/tools/patchscript
--- a/ports/released/gamemakerengine/triga/triga/tools/patchscript
+++ b/ports/released/gamemakerengine/triga/triga/tools/patchscript
@@ -10,6 +10,7 @@ echo "GAMEDIR is set to: $GAMEDIR"
 
 # Patch failure function
 patch_failure() {
+    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
     $ESUDO umount "$TOOLKIT" 2>/dev/null || true
     # Exit script, or return if sourced
     return 1 2>/dev/null || exit 1
@@ -24,6 +25,19 @@ if [ -f "$RUNTIME" ]; then
     $ESUDO mount "$RUNTIME" "$TOOLKIT"
 else
     echo "This port requires the GMToolkit runtime. Please download it."
+    sleep 2
+    patch_failure
+fi
+
+# Mount the dotnet runtime
+DOTNETDIR="$HOME/mono"
+DOTNETFILE="$controlfolder/libs/dotnet-8.0.12.squashfs"
+if [ -f "$DOTNETFILE" ]; then
+    $ESUDO mkdir -p "$DOTNETDIR"
+    $ESUDO umount "$DOTNETDIR" 2>/dev/null || true
+    $ESUDO mount "$DOTNETFILE" "$DOTNETDIR"
+else
+    echo "This port requires the Dotnet runtime. Please download it."
     sleep 2
     patch_failure
 fi
@@ -79,42 +93,46 @@ prepare_files() {
     fi
 }
 
-# Apply a patch to enforce stretching to fill the display
-apply_xdelta() {
-    STEAM_MD5="25f3e9272b8da7d0f34542d34199a02c"
-
-    if [ -f "$DATADIR/data.win" ]; then
-        checksum=$(md5sum "$DATADIR/data.win" | awk '{print $1}')
-        case "$checksum" in
-            "$STEAM_MD5")
-                PATCH="triga_steam.xdelta"
-                ;;
-            *)
-                echo "Unknown data.win checksum: $checksum"
-                echo "Cannot determine appropriate patch"
-                return 0
-                ;;
-        esac
-
-        if [ -f "$GAMEDIR/tools/$PATCH" ]; then
-            output=$($controlfolder/xdelta3 -d -s "$DATADIR/data.win" -f "$GAMEDIR/tools/$PATCH" "$DATADIR/data2.win" 2>&1)
-            if [ $? -eq 0 ]; then
-                echo "Patch applied successfully"
-                echo "$output"
-                rm "$DATADIR/data.win" && mv "$DATADIR/data2.win" "$DATADIR/data.win"
-                sleep 1
-            else
-                echo "Failed to apply patch"
-                echo "$output"
-                return 1
-            fi
-        else
-            echo "Patch file not found: $GAMEDIR/tools/$PATCH"
-        fi
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
     else
-        echo "data.win not found in $DATADIR"
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
+# Externalize game textures with compression
+dump_textures() {
+    # Purge cache before operations
+    [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+
+    # Begin texture operations
+    if ! dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        dump "$DATADIR/data.win" \
+        -e "$DATADIR/textures" "$DATADIR/game.droid"; then
+        echo "[DOTNET]: Texture dumping failed to apply."
         return 1
     fi
+
+    # Cleanup & move textures
+    rm -f "$DATADIR/data.win"
+    [ -d "$SAVEDIR/textures" ] && rm -rf "$SAVEDIR/textures"
+    mv "$DATADIR/textures" "$SAVEDIR/textures"
+
+    # Final cleanup
+    [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
 }
 
 compress_audio() {
@@ -144,14 +162,12 @@ zip_archive() {
 process_game() {
     echo "Preparing game..."
     prepare_files || { patch_failure; return 1; }
-    
-    echo "Applying xdelta patch..."
-    apply_xdelta || { patch_failure; return 1; }
-
+    echo "Toggling GeneralInfo flags..."
+    set_flags || { patch_failure; return 1; }
+    echo "Externalizing textures..."
+    dump_textures || { patch_failure; return 1; }
     echo "Compressing audio..."
     compress_audio || { patch_failure; return 1; }
-
-    sleep 1
     echo "Finishing up..."
     zip_archive || { patch_failure; return 1; }
 }
@@ -165,4 +181,5 @@ else
 fi
 
 # Unmount runtimes
+$ESUDO umount "$DOTNETDIR" 2>/dev/null || true
 $ESUDO umount "$TOOLKIT" 2>/dev/null || true
