[SPINELASHER] Use toggleflags.csx

diff --git a/ports/released/gamemakerengine/spinelasher/spinelasher/tools/patchscript b/ports/released/gamemakerengine/spinelasher/spinelasher/tools/patchscript
--- a/ports/released/gamemakerengine/spinelasher/spinelasher/tools/patchscript
+++ b/ports/released/gamemakerengine/spinelasher/spinelasher/tools/patchscript
@@ -79,6 +79,26 @@ prepare_files() {
     fi
 }
 
+# Toggle GeneralInfo flags via envars - see https://github.com/UnderminersTeam/UndertaleModTool/blob/master/UndertaleModLib/Models/UndertaleGeneralInfo.cs for options
+set_flags() {
+    export SET_FLAGS="Fullscreen"
+    export CLEAR_FLAGS="Scale"
+    dotnet "$TOOLKIT/utmt-cli/UndertaleModCli.dll" \
+        load "$DATADIR/data.win" \
+        -s "$GAMEDIR/tools/toggleflags.csx" \
+        -o "$DATADIR/data2.win"
+        
+    if [ $? -ne 0 ]; then
+        echo "Failed to toggle info flags."
+        return 1
+    else
+        echo "Successfully toggled info flags."
+        rm -f "$DATADIR/data.win"
+        mv "$DATADIR/data2.win" "$DATADIR/data.win"
+        [ -d "$TMPDIR" ] && rm -rf "$TMPDIR"/*
+    fi
+}
+
 compress_audio() {
     # Test for data.win
     if [ -f "$DATADIR/data.win" ]; then
